USE [GD1C2022]

DROP TABLE [MANTECA].[BI_Auto]
DROP TABLE [MANTECA].[BI_Piloto]
DROP TABLE [MANTECA].[BI_Carrera]
DROP TABLE [MANTECA].[BI_Sector]
DROP TABLE [MANTECA].[BI_Motor]
DROP TABLE [MANTECA].[BI_Neumatico]
DROP TABLE [MANTECA].[BI_Caja_de_cambios]
DROP TABLE [MANTECA].[BI_Tipo_incidente]
DROP TABLE [MANTECA].[BI_Fecha]
DROP TABLE [MANTECA].[BI_Medicion]
DROP TABLE [MANTECA].[BI_Parada_en_box]
DROP TABLE [MANTECA].[BI_Freno]
DROP TABLE [MANTECA].[BI_Incidente]

DROP VIEW [MANTECA].[desgaste]
DROP VIEW [MANTECA].[mejor_tiempo_vuelta]
DROP VIEW [MANTECA].[mayor_consumo_combustible_promedio]
DROP VIEW [MANTECA].[maxima_velocidad_x_auto_x_sector_x_circuito]
DROP VIEW [MANTECA].[tiempo_promedio_en_parada_x_escuderia]
DROP VIEW [MANTECA].[cantidad_paradas_x_circuito_x_escuderia_x_anio]
DROP VIEW [MANTECA].[top_3_circuitos_con_mayor_tiempo_de_paradas]
DROP VIEW [MANTECA].[top_3_circuitos_mas_peligrosos]
DROP VIEW [MANTECA].[promedio_de_incidentes_anual_x_escuderia_tipo_de_sector]