USE [GD1C2022]


ALTER TABLE [MANTECA].[Auto]
DROP CONSTRAINT FK_ESCUDERIA 

ALTER TABLE [MANTECA].[Medicion]
DROP CONSTRAINT FK_CARRERA 

ALTER TABLE [MANTECA].[Medicion]
DROP CONSTRAINT FK_SECTOR_MEDICION 

ALTER TABLE [MANTECA].[Medicion]
DROP CONSTRAINT FK_AUTO_MEDICION 

--Medicion Auto
ALTER TABLE [MANTECA].[Medicion_Auto]
DROP CONSTRAINT FK_NRO_AUTO 

ALTER TABLE [MANTECA].[Medicion_Auto]
DROP CONSTRAINT FK_PILOTO 

ALTER TABLE [MANTECA].[Medicion_Auto]
DROP CONSTRAINT FK_MEDICION
--Medicion Motor
ALTER TABLE [MANTECA].[Medicion_Motor]
DROP CONSTRAINT FK_MOTOR

ALTER TABLE [MANTECA].[Medicion_Motor]
DROP CONSTRAINT FK_MEDICION_A_MOTOR
--Medicion Neumatico
ALTER TABLE [MANTECA].[Medicion_Neumatico]
DROP CONSTRAINT FK_NEUMATICO 

ALTER TABLE [MANTECA].[Medicion_Neumatico]
DROP CONSTRAINT FK_MEDICION_A_NEUMATICO
--Medicion Freno
ALTER TABLE [MANTECA].[Medicion_Frenos]
DROP CONSTRAINT FK_FRENO 

ALTER TABLE [MANTECA].[Medicion_Frenos]
DROP CONSTRAINT FK_MEDICION_A_FRENOS
--Medicion Caja De Cambios
ALTER TABLE [MANTECA].[Medicion_Caja_De_Cambios]
DROP CONSTRAINT FK_CAJA_CAMBIO 

ALTER TABLE [MANTECA].[Medicion_Caja_De_Cambios]
DROP CONSTRAINT FK_MEDICION_A_CAJA
--Carrera
ALTER TABLE [MANTECA].[Carrera]
DROP CONSTRAINT FK_CIRCUITO_CARRERA 

--Sector
ALTER TABLE [MANTECA].[Sector]
DROP CONSTRAINT FK_CIRCUITO_SECTOR 

--Incidente
ALTER TABLE [MANTECA].[Incidente]
DROP CONSTRAINT FK_SECTOR_INCIDENTE 

--Auto Incidentado
ALTER TABLE [MANTECA].[Auto_Incidentado]
DROP CONSTRAINT FK_INCIDENTE 

ALTER TABLE [MANTECA].[Auto_Incidentado]
DROP CONSTRAINT FK_NUMERO_AUTO 

ALTER TABLE [MANTECA].[Auto_Incidentado]
DROP CONSTRAINT FK_TIPO_INCIDENTE 

--Parada en Box
ALTER TABLE [MANTECA].[Parada_En_Box]
DROP CONSTRAINT FK_AUTO_PARADA 

--Cambio De Neumaticos
ALTER TABLE [MANTECA].[Cambio_De_Neumatico]
DROP CONSTRAINT FK_NEUMATICO_ANTERIOR 

ALTER TABLE [MANTECA].[Cambio_De_Neumatico]
DROP CONSTRAINT FK_NEUMATICO_NUEVO 

ALTER TABLE [MANTECA].[Cambio_De_Neumatico]
DROP CONSTRAINT FK_PARADA 

DROP TABLE MANTECA.auto
DROP TABLE MANTECA.auto_incidentado
DROP TABLE MANTECA.caja_de_cambios
DROP TABLE MANTECA.Cambio_de_neumatico
DROP TABLE MANTECA.carrera
DROP TABLE MANTECA.circuito
DROP TABLE MANTECA.escuderia
DROP TABLE MANTECA.freno
DROP TABLE MANTECA.incidente
DROP TABLE MANTECA.medicion
DROP TABLE MANTECA.medicion_auto
DROP TABLE MANTECA.medicion_caja_de_cambios
DROP TABLE MANTECA.medicion_frenos
DROP TABLE MANTECA.medicion_motor
DROP TABLE MANTECA.medicion_neumatico
DROP TABLE MANTECA.motor
DROP TABLE MANTECA.neumatico
DROP TABLE MANTECA.parada_en_box
DROP TABLE MANTECA.piloto
DROP TABLE MANTECA.sector
DROP TABLE MANTECA.tipo_incidente