USE [GD1C2022]


INSERT INTO [MANTECA].Piloto
(PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO)
SELECT DISTINCT PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO FROM gd_esquema.Maestra;--ok

INSERT INTO [MANTECA].Escuderia
(ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD)
SELECT DISTINCT ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD FROM gd_esquema.Maestra--ok

INSERT INTO [MANTECA].Auto
(AUTO_NUMERO, ID_ESCUDERIA, AUTO_MODELO)
SELECT AUTO_NUMERO, E.ID_ESCUDERIA, AUTO_MODELO FROM gd_esquema.Maestra
JOIN [MANTECA].Escuderia E ON E.ESCUDERIA_NOMBRE = gd_esquema.Maestra.ESCUDERIA_NOMBRE
GROUP BY AUTO_NUMERO, ID_ESCUDERIA, AUTO_MODELO--ok

INSERT INTO [MANTECA].Circuito
(ID_CIRCUITO, CIRCUITO_NOMBRE, CIRCUITO_PAIS)
SELECT DISTINCT CIRCUITO_CODIGO, CIRCUITO_NOMBRE, CIRCUITO_PAIS FROM gd_esquema.Maestra--ok

INSERT INTO [MANTECA].Carrera
(CARRERA_FECHA_INICIO, ID_CARRERA, CARRERA_CLIMA, CARRERA_LONGITUD, VUELTAS_TOTAL, ID_CIRCUITO)
SELECT DISTINCT CARRERA_FECHA, CODIGO_CARRERA, CARRERA_CLIMA, CARRERA_TOTAL_CARRERA, CARRERA_CANT_VUELTAS, C.ID_CIRCUITO FROM gd_esquema.Maestra
JOIN [MANTECA].CIRCUITO C ON C.ID_CIRCUITO=gd_esquema.Maestra.CIRCUITO_CODIGO
GROUP BY CARRERA_FECHA, CODIGO_CARRERA, CARRERA_CLIMA, CARRERA_TOTAL_CARRERA, CARRERA_CANT_VUELTAS, C.ID_CIRCUITO
ORDER BY CODIGO_CARRERA	asc--ok

INSERT INTO [MANTECA].Sector
(ID_SECTOR, SECTOR_TIPO, SECTOR_LONGITUD, ID_CIRCUITO)
SELECT DISTINCT CODIGO_SECTOR, SECTO_TIPO, SECTOR_DISTANCIA, C.ID_CIRCUITO FROM gd_esquema.Maestra
JOIN [MANTECA].CIRCUITO C ON C.ID_CIRCUITO=gd_esquema.Maestra.CIRCUITO_CODIGO
GROUP BY CODIGO_SECTOR, SECTO_TIPO, SECTOR_DISTANCIA, C.ID_CIRCUITO
ORDER BY CODIGO_SECTOR ASC

INSERT INTO [MANTECA].Incidente
(INCIDENTE_BANDERA, ID_SECTOR, INCIDENTE_TIEMPO)
SELECT INCIDENTE_BANDERA, S.ID_SECTOR, INCIDENTE_TIEMPO FROM gd_esquema.Maestra
JOIN [MANTECA].SECTOR S ON S.ID_SECTOR=gd_esquema.Maestra.CODIGO_SECTOR
WHERE INCIDENTE_BANDERA IS NOT NULL
GROUP BY INCIDENTE_BANDERA, S.ID_SECTOR, INCIDENTE_TIEMPO 


INSERT INTO [MANTECA].Tipo_incidente
(TIPO_INCIDENTE)
SELECT INCIDENTE_TIPO  FROM gd_esquema.Maestra
WHERE INCIDENTE_TIPO IS NOT NULL

--------------------------------------AUTO INCIDENTADO-------------------------------------	TODO
INSERT INTO [MANTECA].Auto_incidentado 
(NRO_VUELTA, i.ID_INCIDENTE, a.ID_AUTO, t.ID_TIPO_INCIDENTE)
SELECT INCIDENTE_NUMERO_VUELTA FROM gd_esquema.Maestra
JOIN [MANTECA].Incidente i ON i.INCIDENTE_BANDERA = Maestra.INCIDENTE_BANDERA AND i.INCIDENTE_TIEMPO = Maestra.INCIDENTE_NUMERO_VUELTA
JOIN [MANTECA].Auto a ON a.AUTO_MODELO = Maestra.AUTO_MODELO and A.AUTO_NUMERO = Maestra.AUTO_NUMERO
JOIN [MANTECA].Tipo_incidente t ON t.TIPO_INCIDENTE = Maestra.INCIDENTE_TIPO

INSERT INTO [MANTECA].Parada_En_box
(NUMERO_VUELTA, PARADA_DURACION, ID_AUTO)
SELECT PARADA_BOX_TIEMPO, PARADA_BOX_VUELTA, AUTO_NUMERO FROM gd_esquema.Maestra

INSERT INTO [MANTECA].Medicion_auto
(ID_MEDICION, VUELTA_NUMERO, DISTANCIA_RECORRIDA_VUELTA, POSICION, TIEMPO_DE_VUELTA, VELOCIDAD, COMBUSTIBLE, p.ID_PILOTO, a.ID_AUTO)
SELECT TELE_AUTO_CODIGO, TELE_AUTO_NUMERO_VUELTA, TELE_AUTO_DISTANCIA_VUELTA, TELE_AUTO_POSICION, TELE_AUTO_TIEMPO_VUELTA,
		TELE_AUTO_VELOCIDAD, TELE_AUTO_COMBUSTIBLE FROM gd_esquema.Maestra
JOIN [MANTECA].Piloto p ON p.PILOTO_NOMBRE = Maestra.PILOTO_NOMBRE
JOIN [MANTECA].Auto a ON a.AUTO_MODELO = Maestra.AUTO_MODELO AND a.AUTO_NUMERO = Maestra.AUTO_NUMERO

INSERT INTO [MANTECA].Caja_de_cambios
(CAJA_CAMBIO_MODELO, NRO_SERIE)
SELECT TELE_CAJA_MODELO, TELE_CAJA_NRO_SERIE FROM gd_esquema.Maestra

INSERT INTO [MANTECA].Medicion_caja_de_cambios
(RPM, TEMPERATURA_ACEITE, DESGASTE_PORCENTUAL_ACUMULADO, c.ID_CAJA_CAMBIO)
SELECT TELE_CAJA_RPM, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_DESGASTE FROM gd_esquema.Maestra
JOIN [MANTECA].Caja_de_Cambios c ON c.CAJA_CAMBIO_MODELO = Maestra.TELE_CAJA_MODELO 
						AND c.NRO_SERIE = Maestra.TELE_CAJA_NRO_SERIE 							

INSERT INTO [MANTECA].Motor
(MODELO, NRO_SERIE)
SELECT TELE_MOTOR_MODELO, TELE_MOTOR_NRO_SERIE FROM gd_esquema.Maestra

INSERT INTO [MANTECA].Medicion_Motor
(POTENCIA_MOMENTANEA, RPM, TEMP_ACEITE, TEMP_AGUA, m.ID_MOTOR)
SELECT TELE_MOTOR_POTENCIA, TELE_MOTOR_RPM, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA FROM gd_esquema.Maestra
JOIN [MANTECA].Motor m ON m.MODELO = Maestra.TELE_MOTOR_MODELO
			AND m.NRO_SERIE = Maestra.TELE_MOTOR_NRO_SERIE

INSERT INTO [MANTECA].Neumatico
(NRO_SERIE, n.NEUMATICO_TIPO)
SELECT TELE_NEUMATICO1_NRO_SERIE FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.NEUMATICO1_NRO_SERIE_NUEVO
INSERT INTO [MANTECA].Neumatico
(NRO_SERIE, n.NEUMATICO_TIPO)
SELECT TELE_NEUMATICO2_NRO_SERIE FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.NEUMATICO2_NRO_SERIE_NUEVO
INSERT INTO [MANTECA].Neumatico
(NRO_SERIE, n.NEUMATICO_TIPO)
SELECT TELE_NEUMATICO3_NRO_SERIE FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.NEUMATICO3_NRO_SERIE_NUEVO
INSERT INTO [MANTECA].Neumatico
(NRO_SERIE, n.NEUMATICO_TIPO)
SELECT TELE_NEUMATICO4_NRO_SERIE FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.NEUMATICO4_NRO_SERIE_NUEVO

INSERT INTO [MANTECA].Medicion_Neumatico
(POSICION, PRESION, PROFUNDIDAD, TEMPERATURA, n.ID_NEUMATICO)
SELECT TELE_NEUMATICO1_POSICION, TELE_NEUMATICO1_PRESION, TELE_NEUMATICO1_PROFUNDIDAD, TELE_NEUMATICO1_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.TELE_NEUMATICO1_NRO_SERIE
INSERT INTO [MANTECA].Medicion_Neumatico
(POSICION, PRESION, PROFUNDIDAD, TEMPERATURA, n.ID_NEUMATICO)
SELECT TELE_NEUMATICO2_POSICION, TELE_NEUMATICO2_PRESION, TELE_NEUMATICO2_PROFUNDIDAD, TELE_NEUMATICO2_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.TELE_NEUMATICO2_NRO_SERIE
INSERT INTO [MANTECA].Medicion_Neumatico
(POSICION, PRESION, PROFUNDIDAD, TEMPERATURA, n.ID_NEUMATICO)
SELECT TELE_NEUMATICO3_POSICION, TELE_NEUMATICO3_PRESION, TELE_NEUMATICO3_PROFUNDIDAD, TELE_NEUMATICO3_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.TELE_NEUMATICO3_NRO_SERIE
INSERT INTO [MANTECA].Medicion_Neumatico
(POSICION, PRESION, PROFUNDIDAD, TEMPERATURA, n.ID_NEUMATICO)
SELECT TELE_NEUMATICO4_POSICION, TELE_NEUMATICO4_PRESION, TELE_NEUMATICO4_PROFUNDIDAD, TELE_NEUMATICO4_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.TELE_NEUMATICO4_NRO_SERIE

INSERT INTO [MANTECA].Freno
(NRO_SERIE, TAMANIO_DISCO)
SELECT TELE_FRENO1_NRO_SERIE, TELE_FRENO1_TAMANIO_DISCO FROM gd_esquema.Maestra
INSERT INTO [MANTECA].Freno
(NRO_SERIE, TAMANIO_DISCO)
SELECT TELE_FRENO2_NRO_SERIE, TELE_FRENO2_TAMANIO_DISCO FROM gd_esquema.Maestra
INSERT INTO [MANTECA].Freno
(NRO_SERIE, TAMANIO_DISCO)
SELECT TELE_FRENO3_NRO_SERIE, TELE_FRENO3_TAMANIO_DISCO FROM gd_esquema.Maestra
INSERT INTO [MANTECA].Freno
(NRO_SERIE, TAMANIO_DISCO)
SELECT TELE_FRENO4_NRO_SERIE, TELE_FRENO4_TAMANIO_DISCO FROM gd_esquema.Maestra

INSERT INTO [MANTECA].Medicion_frenos
(POSICION, TEMPERATURA, f.ID_FRENO)
SELECT TELE_FRENO1_POSICION, TELE_FRENO1_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Freno f ON f.NRO_SERIE = Maestra.TELE_FRENO1_NRO_SERIE
			AND f.TAMANIO_DISCO = Maestra.TELE_FRENO1_TAMANIO_DISCO
INSERT INTO [MANTECA].Medicion_frenos
(POSICION, TEMPERATURA, f.ID_FRENO)
SELECT TELE_FRENO2_POSICION, TELE_FRENO2_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Freno f ON f.NRO_SERIE = Maestra.TELE_FRENO2_NRO_SERIE
			AND f.TAMANIO_DISCO = Maestra.TELE_FRENO2_TAMANIO_DISCO
INSERT INTO [MANTECA].Medicion_frenos
(POSICION, TEMPERATURA, f.ID_FRENO)
SELECT TELE_FRENO3_POSICION, TELE_FRENO3_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Freno f ON f.NRO_SERIE = Maestra.TELE_FRENO3_NRO_SERIE
			AND f.TAMANIO_DISCO = Maestra.TELE_FRENO3_TAMANIO_DISCO
INSERT INTO [MANTECA].Medicion_frenos
(POSICION, TEMPERATURA, f.ID_FRENO)
SELECT TELE_FRENO4_POSICION, TELE_FRENO4_TEMPERATURA FROM gd_esquema.Maestra
JOIN [MANTECA].Freno f ON f.NRO_SERIE = Maestra.TELE_FRENO4_NRO_SERIE
			AND f.TAMANIO_DISCO = Maestra.TELE_FRENO4_TAMANIO_DISCO

INSERT INTO [MANTECA].Cambio_De_Neumatico
(POSICION, p.ID_PARADA, n2.ID_NEUMATICO_ANTERIOR, n.ID_NEUMATICO_NUEVO)
SELECT TELE_NEUMATICO1_POSICION FROM gd_esquema.Maestra
JOIN [MANTECA].Neumatico n ON n.NRO_SERIE = Maestra.NEUMATICO1_NRO_SERIE_NUEVO
				AND n.NEUMATICO_TIPO = Maestra.NEUMATICO1_TIPO_NUEVO
JOIN [MANTECA].Neumatico n2 ON n.NRO_SERIE = Maestra.NEUMATICO1_NRO_SERIE_VIEJO
				  AND n.NEUMATICO_TIPO = Maestra.NEUMATICO1_TIPO_VIEJO
JOIN [MANTECA].Auto a ON a.AUTO_MODELO = Maestra.AUTO_MODELO AND a.AUTO_NUMERO = Maestra.AUTO_NUMERO
JOIN [MANTECA].Parada_En_Box p ON p.PARADA_DURACION = Maestra.PARADA_BOX_TIEMPO
					AND p.NUMERO_VUELTA = Maestra.PARADA_BOX_VUELTA
					AND p.ID_AUTO = a.id_auto

INSERT INTO [MANTECA].Medicion
(c.ID_CARRERA, ID_SECTOR, DISTANCIA_RECORRIDA_CARRERA, a.ID_AUTO)
SELECT CODIGO_SECTOR, TELE_AUTO_DISTANCIA_CARRERA FROM gd_esquema.Maestra
JOIN [MANTECA].Carrera c ON c.CARRERA_FECHA_INICIO = Maestra.CARRERA_FECHA AND c.CARRERA_LONGITUD = Maestra.CARRERA_TOTAL_CARRERA
				AND c.VUELTAS_TOTAL = Maestra.CARRERA_CANT_VUELTAS AND c.CARRERA_CLIMA = Maestra.CARRERA_CLIMA
JOIN [MANTECA].Auto a ON a.AUTO_MODELO = Maestra.AUTO_MODELO AND a.AUTO_NUMERO = Maestra.AUTO_NUMERO