USE [GD1C2022]

CREATE TABLE [MANTECA].[BI_Fecha] (
	ID_FECHA int NOT NULL IDENTITY (1, 1) CONSTRAINT PK_Fecha PRIMARY KEY,
	FECHA_ANIO INT,
	FECHA_MES INT,
	FECHA_DIA INT,
	FECHA_CUATRIMESTRE TINYINT
);

CREATE TABLE [MANTECA].[BI_Auto] (
    id_auto INT NOT NULL,
	id_escuderia INT,
    PRIMARY KEY (id_auto)
);

CREATE TABLE [MANTECA].[BI_Escuderia] (
    id_escuderia INT NOT NULL,
	nombre nvarchar(255),
    PRIMARY KEY (id_escuderia)
);

CREATE TABLE [MANTECA].[BI_Piloto] (
    id_piloto INT NOT NULL,
    PRIMARY KEY (id_piloto),
);

CREATE TABLE [MANTECA].[BI_Tipo_Neumatico](
	id_tipo_neumatico INT IDENTITY(1,1) NOT NULL,
	descripcion nvarchar(255)
	PRIMARY KEY (id_tipo_neumatico)
);

CREATE TABLE [MANTECA].[BI_Tipo_Sector] (
	id_tipo_sector INT IDENTITY(1,1) NOT NULL,
	descripcion nvarchar(255),
	PRIMARY KEY (id_tipo_sector)
);

CREATE TABLE [MANTECA].[BI_Circuito] (
    id_circuito INT NOT NULL,
	id_carrera INT NOT NULL,
    fecha_inicio DATE NOT NULL,
    PRIMARY KEY (id_carrera)
);

CREATE TABLE [MANTECA].[BI_Tipo_incidente] (
    id_tipo_incidente INT IDENTITY(1,1) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    PRIMARY KEY (id_tipo_incidente)
);

CREATE TABLE [MANTECA].[BI_Parada_en_box] (
	id_parada INT,
    id_circuito INT NOT NULL,
    id_auto INT NOT NULL,
	id_escuderia INT NOT NULL,
    id_fecha INT NOT NULL,
    duracion DECIMAL(18,2)  NULL,
    PRIMARY KEY (id_parada,id_circuito,id_auto,id_escuderia,id_fecha)
);

CREATE TABLE [MANTECA].[BI_Incidente] (
	id_circuito INT NOT NULL,
    id_tipo_sector INT NOT NULL,
	id_escuderia INT NOT NULL,
    id_fecha INT NOT NULL,
    id_tipo_incidente INT NOT NULL,
	PRIMARY KEY (id_circuito,id_tipo_sector,id_escuderia,id_fecha,id_tipo_incidente)
);

CREATE TABLE [MANTECA].[BI_Medicion] ( --circuito,tiposector?,fecha,tipoNeumatico?????,escuderia,auto
    id_fecha INT not NULL,
    --id_neumatico INT NOT NULL,
    id_escuderia INT NOT NULL,
    id_auto INT NOT NULL,
    id_tipo_sector INT NOT NULL,
    id_circuito INT NOT NULL,
    combustible DECIMAL(18,2) NOT NULL,
    --nro_vuelta DECIMAL(18,0) NOT NULL,
    --distancia_recorrida_en_vuelta DECIMAL(18,2) NOT NULL,
    maxVelocidadFrenada DECIMAL(18,2) NOT NULL,
	maxVelocidadCurva DECIMAL(18,2) NOT NULL,
	maxVelocidadRecta DECIMAL(18,2) NOT NULL,
    tiempo_de_vuelta DECIMAL(18,10) NOT NULL,
    motor_potencia_momentanea DECIMAL(18,6) NOT NULL,
    --neumatico_profundidad DECIMAL(18,6) NOT NULL,
	--neumatico_posicion nvarchar(255) NOT NULL,
    --freno_grosor_pastilla DECIMAL(18,2) NOT NULL,
	--freno_posicion nvarchar(255) NOT NULL,
    caja_de_cambios_desgaste_porcentual_acumulado DECIMAL(18,2) NOT NULL,
	neum1_desgaste DECIMAL (18,2) NOT NULL,
	neum2_desgaste DECIMAL (18,2) NOT NULL,
	neum3_desgaste DECIMAL (18,2) NOT NULL,
	neum4_desgaste DECIMAL (18,2) NOT NULL,
	freno1_desgaste DECIMAL (18,2) NOT NULL,
    freno2_desgaste DECIMAL (18,2) NOT NULL,
	freno3_desgaste DECIMAL (18,2) NOT NULL,
	freno4_desgaste DECIMAL (18,2) NOT NULL,
	PRIMARY KEY (id_fecha,id_escuderia,id_auto,id_tipo_sector,id_circuito)
);

INSERT INTO MANTECA.BI_Medicion
(id_fecha, id_escuderia, id_auto, /*id_tipo_sector,*/ id_circuito, combustible, maxVelocidadFrenada, maxVelocidadCurva, maxVelocidadRecta, tiempo_de_vuelta, motor_potencia_momentanea, caja_de_cambios_desgaste_porcentual_acumulado, neum1_desgaste)
SELECT DISTINCT F.id_fecha,
	   BA.id_escuderia,
	   BA.id_auto,
	   --TS.id_tipo_sector,
	   BC.id_circuito,
	   ((SELECT COMBUSTIBLE FROM MANTECA.Medicion_Auto MA2
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=MA2.ID_MEDICION
		WHERE MA2.DISTANCIA_RECORRIDA_VUELTA=0 AND MA2.ID_AUTO=M.ID_AUTO AND MA2.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA
		GROUP BY COMBUSTIBLE, ma2.ID_AUTO, VUELTA_NUMERO)-COMBUSTIBLE/*(SELECT COMBUSTIBLE FROM MANTECA.Medicion_Auto MA3
														   LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=MA3.ID_MEDICION
													       WHERE MA3.DISTANCIA_RECORRIDA_VUELTA=149 AND MA3.ID_AUTO=M.ID_AUTO AND MA3.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA
														   GROUP BY COMBUSTIBLE, MA3.ID_AUTO, VUELTA_NUMERO)*/) AS 'CONSUMO COMBUSTIBLE POR VUELTA',
	   (SELECT MAX(VELOCIDAD) FROM MANTECA.Medicion_Auto MVF
	    JOIN MANTECA.MEDICION MF ON MF.ID_MEDICION=MVF.ID_MEDICION
		WHERE MVF.ID_AUTO=M.ID_AUTO AND MVF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_SECTOR IN (SELECT ID_SECTOR FROM MANTECA.SECTOR WHERE SECTOR_TIPO='Frenada')) as 'Velocidad Frenada',
		(SELECT MAX(VELOCIDAD) FROM MANTECA.Medicion_Auto MVC
	    JOIN MANTECA.MEDICION MC ON MC.ID_MEDICION=MVC.ID_MEDICION
		WHERE MVC.ID_AUTO=M.ID_AUTO AND MVC.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MC.ID_SECTOR IN (SELECT ID_SECTOR FROM MANTECA.SECTOR WHERE SECTOR_TIPO='Curva')) as 'Velocidad Curva',
		(SELECT MAX(VELOCIDAD) FROM MANTECA.Medicion_Auto MVR
	    JOIN MANTECA.MEDICION MR ON MR.ID_MEDICION=MVR.ID_MEDICION
		WHERE MVR.ID_AUTO=M.ID_AUTO AND MVR.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MR.ID_SECTOR IN (SELECT ID_SECTOR FROM MANTECA.SECTOR WHERE SECTOR_TIPO='Recta')) as 'Velocidad Recta',
		MA.VUELTA_NUMERO,
		MA.TIEMPO_DE_VUELTA,
		((SELECT POTENCIA_MOMENTANEA FROM MANTECA.Medicion_Motor MM
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=MM.ID_MEDICION
		LEFT JOIN MANTECA.Medicion_Auto MAI ON MM.ID_MEDICION=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA
		GROUP BY POTENCIA_MOMENTANEA, MAI.ID_AUTO, VUELTA_NUMERO)-(SELECT POTENCIA_MOMENTANEA FROM MANTECA.Medicion_Motor MMF
														   LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=MMF.ID_MEDICION
														   LEFT JOIN MANTECA.Medicion_Auto MAF ON MMF.ID_MEDICION=MAF.ID_MEDICION
													       WHERE MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA
														   GROUP BY POTENCIA_MOMENTANEA, MAF.ID_AUTO, VUELTA_NUMERO)) AS 'DESGASTE MOTOR POR VUELTA',
		MC.DESGASTE_PORCENTUAL_ACUMULADO,
		((SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N1
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=N1.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON N1.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
		GROUP BY PROFUNDIDAD, MAI.ID_AUTO, VUELTA_NUMERO, N1.POSICION)-(SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N1
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE N1.MEDICION_AUTO=M.ID_MEDICION  AND N1.POSICION='Delantero Izquierdo' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY PROFUNDIDAD, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ N1.POSICION)) AS 'DESGASTE NEUMATICO 1',
		 ((SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N2
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=N2.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON N2.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND N2.POSICION='Delantero Derecho'
		GROUP BY PROFUNDIDAD, MAI.ID_AUTO, VUELTA_NUMERO, N2.POSICION)-(SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N2
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE N2.MEDICION_AUTO=M.ID_MEDICION  AND N2.POSICION='Delantero Derecho' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY PROFUNDIDAD, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ N2.POSICION)) AS 'DESGASTE NEUMATICO 2',
		((SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N3
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=N3.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON N3.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND N3.POSICION='Trasero Izquierdo'
		GROUP BY PROFUNDIDAD, MAI.ID_AUTO, VUELTA_NUMERO, N3.POSICION)-(SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N3
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE N3.MEDICION_AUTO=M.ID_MEDICION  AND N3.POSICION='Trasero Izquierdo' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY PROFUNDIDAD, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ N3.POSICION)) AS 'DESGASTE NEUMATICO 3',
		((SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N4
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=N4.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON N4.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND N4.POSICION='Trasero Derecho'
		GROUP BY PROFUNDIDAD, MAI.ID_AUTO, VUELTA_NUMERO, N4.POSICION)-(SELECT PROFUNDIDAD FROM MANTECA.Medicion_Neumatico N4
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE N4.MEDICION_AUTO=M.ID_MEDICION  AND N4.POSICION='Trasero Derecho' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY PROFUNDIDAD, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ N4.POSICION)) AS 'DESGASTE NEUMATICO 4',
		((SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F1
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=F1.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON F1.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND F1.POSICION='Delantero Izquierdo'
		GROUP BY GROSOR_PASTILLA, MAI.ID_AUTO, VUELTA_NUMERO, F1.POSICION)-(SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F1
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE F1.MEDICION_AUTO=M.ID_MEDICION  AND F1.POSICION='Delantero Izquierdo' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY GROSOR_PASTILLA, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ F1.POSICION)) AS 'DESGASTE FRENO 1',
		((SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F2
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=F2.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON F2.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND F2.POSICION='Delantero Derecho'
		GROUP BY GROSOR_PASTILLA, MAI.ID_AUTO, VUELTA_NUMERO, F2.POSICION)-(SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F2
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE F2.MEDICION_AUTO=M.ID_MEDICION  AND F2.POSICION='Delantero Derecho' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY GROSOR_PASTILLA, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ F2.POSICION)) AS 'DESGASTE FRENO 2',
		((SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F3
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=F3.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON F3.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND F3.POSICION='Trasero Izquierdo'
		GROUP BY GROSOR_PASTILLA, MAI.ID_AUTO, VUELTA_NUMERO, F3.POSICION)-(SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F3
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE F3.MEDICION_AUTO=M.ID_MEDICION  AND F3.POSICION='Trasero Izquierdo' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY GROSOR_PASTILLA, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ F3.POSICION)) AS 'DESGASTE FRENO 3',
		((SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F4
		left JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=F4.MEDICION_AUTO
		LEFT JOIN MANTECA.Medicion_Auto MAI ON F4.MEDICION_AUTO=MAI.ID_MEDICION
		WHERE MAI.DISTANCIA_RECORRIDA_VUELTA=0 AND MAI.ID_AUTO=M.ID_AUTO AND MAI.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MI.ID_CARRERA=M.ID_CARRERA AND F4.POSICION='Trasero Derecho'
		GROUP BY GROSOR_PASTILLA, MAI.ID_AUTO, VUELTA_NUMERO, F4.POSICION)-(SELECT GROSOR_PASTILLA FROM MANTECA.Medicion_Frenos F4
																        --LEFT JOIN MANTECA.Medicion MF ON MF.ID_MEDICION=N1.ID_MEDICION
																		--LEFT JOIN MANTECA.Medicion_Auto MAF ON N1.ID_MEDICION=MAF.ID_MEDICION
																	    WHERE F4.MEDICION_AUTO=M.ID_MEDICION  AND F4.POSICION='Trasero Derecho' --MAF.DISTANCIA_RECORRIDA_VUELTA=149 AND MAF.ID_AUTO=M.ID_AUTO AND MAF.VUELTA_NUMERO=MA.VUELTA_NUMERO AND MF.ID_CARRERA=M.ID_CARRERA AND N1.POSICION='Delantero Izquierdo'
																		GROUP BY GROSOR_PASTILLA, /*MAF.ID_AUTO, VUELTA_NUMERO,*/ F4.POSICION)) AS 'DESGASTE FRENO 4'			
FROM MANTECA.Medicion M
JOIN MANTECA.BI_Auto BA ON M.id_auto=BA.id_auto
JOIN MANTECA.BI_Circuito BC ON M.ID_CARRERA=BC.id_carrera
--JOIN MANTECA.Sector S ON S.ID_SECTOR=M.ID_SECTOR
--JOIN MANTECA.BI_Tipo_Sector TS ON TS.descripcion=S.SECTOR_TIPO
JOIN MANTECA.BI_Fecha f ON f.FECHA_ANIO = YEAR(BC.fecha_inicio) AND f.FECHA_MES = MONTH(BC.fecha_inicio) AND f.FECHA_DIA = DAY(BC.fecha_inicio)
JOIN MANTECA.Medicion_Auto MA ON MA.ID_MEDICION=M.ID_MEDICION
JOIN MANTECA.Medicion_Caja_De_Cambios MC ON MC.ID_MEDICION=M.ID_MEDICION
WHERE MA.DISTANCIA_RECORRIDA_VUELTA=149
GROUP BY F.id_fecha, BA.id_escuderia, BA.id_auto, /*TS.id_tipo_sector,*/ BC.id_circuito, COMBUSTIBLE, M.ID_MEDICION,M.ID_AUTO,MA.VUELTA_NUMERO, M.ID_CARRERA, MA.TIEMPO_DE_VUELTA, MC.DESGASTE_PORCENTUAL_ACUMULADO
ORDER BY 4 DESC ,3 DESC, 9 asc   	

SELECT * FROM MANTECA.Medicion_Neumatico N
JOIN MANTECA.Medicion_Auto M ON N.ID_MEDICION=M.ID_MEDICION
WHERE N.POSICION='Delantero Izquierdo' AND 

SELECT M.ID_AUTO, M.VUELTA_NUMERO, MAX(M.velocidad) from Manteca.Medicion_Auto M
JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=M.ID_MEDICION
WHERE MI.ID_SECTOR IN (SELECT ID_SECTOR FROM manteca.SECTOR WHERE SECTOR_TIPO='Frenada')
GROUP BY M.ID_AUTO, M.VUELTA_NUMERO
ORDER BY 1,2

SELECT M.ID_AUTO, M.VUELTA_NUMERO, MAX(M.velocidad) from Manteca.Medicion_Auto M
JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=M.ID_MEDICION
WHERE MI.ID_SECTOR IN (SELECT ID_SECTOR FROM manteca.SECTOR WHERE SECTOR_TIPO='Recta')
GROUP BY M.ID_AUTO, M.VUELTA_NUMERO
ORDER BY 1,2

SELECT M.ID_AUTO, M.VUELTA_NUMERO, MAX(M.velocidad) from Manteca.Medicion_Auto M
JOIN MANTECA.Medicion MI ON MI.ID_MEDICION=M.ID_MEDICION
WHERE MI.ID_SECTOR IN (SELECT ID_SECTOR FROM manteca.SECTOR WHERE SECTOR_TIPO='Curva')
GROUP BY M.ID_AUTO, M.VUELTA_NUMERO
ORDER BY 1,2

SELECT ma.ID_AUTO,m.ID_CARRERA,ma.VUELTA_NUMERO,ma.DISTANCIA_RECORRIDA_VUELTA,mn.PROFUNDIDAD,mn.POSICION, MN.PROFUNDIDAD FROM MANTECA.Medicion_Neumatico MN
JOIN MANTECA.Medicion M ON m.ID_MEDICION = mn.ID_MEDICION
JOIN MANTECA.Medicion_Auto ma ON ma.ID_MEDICION = mn.ID_MEDICION
WHERE mn.POSICION='Delantero Derecho' and DISTANCIA_RECORRIDA_VUELTA = 149 OR DISTANCIA_RECORRIDA_VUELTA = 0 AND mn.POSICION='Delantero Derecho'
ORDER BY 1 DESC, 2 DESC, 3 DESC

SELECT AVG( ma.combustible) , ci.CIRCUITO_NOMBRE FROM MANTECA.Medicion_Auto ma
JOIN MANTECA.Medicion m ON m.ID_MEDICION = ma.ID_MEDICION
JOIN MANTECA.Carrera c ON m.ID_CARRERA = c.ID_CARRERA
JOIN MANTECA.Circuito ci ON ci.ID_CIRCUITO = c.ID_CIRCUITO 
WHERE DISTANCIA_RECORRIDA_VUELTA = 150
GROUP BY ci.CIRCUITO_NOMBRE
ORDER BY 1 DESC

ALTER TABLE [MANTECA].[BI_Medicion]
ADD
FOREIGN KEY (id_fecha) REFERENCES [MANTECA].BI_Fecha,
FOREIGN KEY (id_escuderia) REFERENCES [MANTECA].BI_Escuderia,
FOREIGN KEY (id_auto) REFERENCES [MANTECA].BI_Auto,
FOREIGN KEY (id_tipo_sector) REFERENCES [MANTECA].BI_Tipo_Sector,
FOREIGN KEY (id_circuito) REFERENCES [MANTECA].BI_Circuito


ALTER TABLE [MANTECA].[BI_Parada_en_box]
ADD
FOREIGN KEY (id_fecha) REFERENCES [MANTECA].BI_Fecha,
FOREIGN KEY (id_escuderia) REFERENCES [MANTECA].BI_Escuderia,
FOREIGN KEY (id_circuito) REFERENCES [MANTECA].BI_Circuito

ALTER TABLE [MANTECA].[BI_Incidente]
ADD
FOREIGN KEY (id_tipo_sector) REFERENCES [MANTECA].BI_Tipo_Sector,
FOREIGN KEY (id_circuito) REFERENCES [MANTECA].BI_Circuito,
FOREIGN KEY (id_escuderia) REFERENCES [MANTECA].BI_Escuderia,
FOREIGN KEY (id_fecha) REFERENCES [MANTECA].BI_Fecha,
FOREIGN KEY (id_tipo_incidente) REFERENCES [MANTECA].BI_Tipo_incidente


INSERT INTO MANTECA.BI_Fecha
(FECHA_ANIO, FECHA_MES, FECHA_DIA, FECHA_CUATRIMESTRE)
SELECT (YEAR(CARRERA_FECHA_INICIO)) AS 'ANIO', MONTH(CARRERA_FECHA_INICIO) 'MES', DAY(CARRERA_FECHA_INICIO) 'DIA', CASE MONTH(CARRERA_FECHA_INICIO)
       WHEN '1' then '1'
       WHEN '2' then '1'
       WHEN '3' then '1'
       WHEN '4' then '1'
       WHEN '5' then '2'
       WHEN '6'  then '2'
       WHEN '7' then '2'
       WHEN '8' then '2'
       WHEN '9' then '3'
       WHEN '10' then '3'
       WHEN '11' then '3'
       WHEN '12' then '3'
     END  AS 'CUATRIMESTRE'
     from MANTECA.Carrera
ORDER BY 1, 2, 3, 4

INSERT INTO MANTECA.BI_Auto
(id_auto, id_escuderia)
SELECT a.ID_AUTO, a.ID_ESCUDERIA
FROM MANTECA.Auto a
JOIN MANTECA.Escuderia e ON e.ID_ESCUDERIA = a.ID_ESCUDERIA

INSERT INTO MANTECA.BI_Escuderia
(id_escuderia,nombre)
SELECT ID_ESCUDERIA,ESCUDERIA_NOMBRE
FROM MANTECA.Escuderia

INSERT INTO MANTECA.BI_Piloto
(id_piloto)
SELECT ID_PILOTO FROM MANTECA.PILOTO 

INSERT INTO MANTECA.BI_Tipo_Neumatico
(descripcion)
SELECT DISTINCT NEUMATICO_TIPO FROM MANTECA.Neumatico

INSERT INTO MANTECA.BI_Tipo_Sector
(descripcion)
SELECT DISTINCT SECTOR_TIPO FROM MANTECA.Sector

INSERT INTO MANTECA.BI_Circuito
(id_carrera,fecha_inicio, id_circuito)
SELECT ID_CARRERA,CARRERA_FECHA_INICIO, ca.ID_CIRCUITO FROM MANTECA.Carrera ca
JOIN MANTECA.Circuito c ON c.ID_CIRCUITO = ca.ID_CIRCUITO

INSERT INTO MANTECA.BI_Tipo_incidente
(tipo)
SELECT DISTINCT TIPO_INCIDENTE FROM MANTECA.Tipo_Incidente

INSERT INTO MANTECA.BI_Parada_en_box
(id_parada, id_circuito, id_auto, id_escuderia, id_fecha, duracion)
SELECT DISTINCT pb.ID_PARADA, pb.ID_CIRCUITO, pb.ID_AUTO,a.id_escuderia, f.ID_FECHA ,pb.PARADA_DURACION 
FROM MANTECA.Parada_En_Box pb 
JOIN MANTECA.BI_Auto a ON a.id_auto = pb.ID_AUTO
JOIN MANTECA.BI_Circuito c ON pb.ID_CIRCUITO = c.id_circuito
JOIN MANTECA.BI_Fecha f ON f.FECHA_ANIO = YEAR(c.fecha_inicio) AND f.FECHA_MES = MONTH(c.fecha_inicio) AND f.FECHA_DIA = DAY(c.fecha_inicio)
GROUP BY pb.ID_PARADA, pb.ID_AUTO, pb.PARADA_DURACION, f.ID_FECHA,pb.ID_CIRCUITO,a.id_escuderia

INSERT INTO MANTECA.BI_Incidente 
( id_circuito, id_tipo_sector,id_escuderia, id_fecha,id_tipo_incidente)
SELECT s.ID_CIRCUITO ,ts.id_tipo_sector, a.id_escuderia,  f.ID_FECHA, bti.id_tipo_incidente  
FROM MANTECA.Auto_Incidentado ai
JOIN MANTECA.BI_Auto a ON ai.ID_AUTO = a.id_auto
JOIN MANTECA.Sector s ON ai.ID_SECTOR = s.ID_SECTOR
JOIN MANTECA.BI_Tipo_Sector ts ON ts.descripcion = s.SECTOR_TIPO
JOIN MANTECA.Tipo_Incidente ti ON ti.ID_TIPO_INCIDENTE = ai.ID_TIPO_INCIDENTE
JOIN MANTECA.BI_Tipo_incidente bti ON bti.tipo = ti.TIPO_INCIDENTE
JOIN MANTECA.BI_Fecha f ON f.FECHA_ANIO = YEAR(ai.carrera_fecha) AND f.FECHA_MES = MONTH(ai.carrera_fecha) AND f.FECHA_DIA = DAY(ai.carrera_fecha)
GROUP BY s.ID_CIRCUITO,ts.id_tipo_sector,a.id_escuderia,f.ID_FECHA,bti.id_tipo_incidente

